#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export PATH="/Applications/dart/dart-sdk/bin:/Users/daniel/tools/androidsdk/tools:/Users/daniel/tools/androidsdk/platform-tools:/Users/daniel/bin:/Users/daniel/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export MANPATH="/usr/local/man:$MANPATH"

source ~/.nvm/nvm.sh
source ~/.datasplice_env
